echo "Killing nodes started by base selection"
rosnode kill /autobed/autobed_state_publisher
rosnode kill /ar_track_alvar
rosnode kill /autobed_occupied_server
rosnode kill /autobed_state_publisher_node
rosnode kill /base_selection
rosnode kill /find_autobed
rosnode kill /find_head
rosnode kill /sm_pr2_servoing
echo "Nodes killed"
echo "Killing nodes started by assistive teleop"
rosnode kill /r_gripper_sensor_controller/event_detector_action_node
rosnode kill /r_gripper_sensor_controller/findContact_action_node
rosnode kill /r_gripper_sensor_controller/forceServo_action_node
rosnode kill /r_gripper_sensor_controller/grab_action_node
rosnode kill /r_gripper_sensor_controller/gripper_action_node
rosnode kill /r_gripper_sensor_controller/release_action_node
rosnode kill /r_gripper_sensor_controller/slipServo_action_node 
rosnode kill /pddl_tasks/adl/ar_tag_tracking_monitor
rosnode kill /right_arm/haptic_mpc 
rosnode kill /right_arm/mpc_teleop 
rosnode kill /right_arm/pr2_arm_kinematics 
rosnode kill /right_arm/robot_haptic_state 
rosnode kill /right_arm/runstop_safe_restart
rosnode kill /right_arm/waypoint_generator
rosnode kill /data_bag
rosnode kill /domain_state_aggregator 
rosnode kill /head_state_throttle
rosnode kill /heartbeat_relay 
rosnode kill /joints_throttle
rosnode kill /kinect_throttle 
rosnode kill /l_grasp_state_monitor 
rosnode kill /l_gripper_sensor_controller_spawner 
rosnode kill /l_gripper_state_throttle 
rosnode kill /mjpeg_server 
rosnode kill /pixel_2_3d 
rosnode kill /r_grasp_state_monitor 
rosnode kill /r_gripper_sensor_controller_spawner
rosnode kill /r_gripper_state_throttle 
rosnode kill /rosapi 
rosnode kill /rosbridge 
rosnode kill /roswww 
rosnode kill /task_planner 
rosnode kill /task_smacher 
rosnode kill /tf2_web_republisher 
rosnode kill /torso_state_throttle 
rosnode kill /tuck_arms_app 
rosnode kill /video_bag 
rosnode kill /left_arm/haptic_mpc 
rosnode kill /left_arm/mpc_teleop 
rosnode kill /left_arm/pr2_arm_kinematics 
rosnode kill /left_arm/robot_haptic_state
rosnode kill /left_arm/runstop_safe_restart
rosnode kill /left_arm/waypoint_generator 
rosnode kill /pcl_filters/box_filter_pcl_manager 
rosnode kill /pcl_filters/outlier_removal 
rosnode kill /pcl_filters/pc_filtered_throttle
rosnode kill /pcl_filters/psx
rosnode kill /pcl_filters/psy
rosnode kill /pcl_filters/psz
rosnode kill /pcl_filters/vfx  
rosnode kill /l_gripper_sensor_controller/event_detector_action_node
rosnode kill /l_gripper_sensor_controller/findContact_action_node 
rosnode kill /l_gripper_sensor_controller/forceServo_action_node 
rosnode kill /l_gripper_sensor_controller/grab_action_node 
rosnode kill /l_gripper_sensor_controller/gripper_action_node 
rosnode kill /l_gripper_sensor_controller/release_action_node 
rosnode kill /l_gripper_sensor_controller/slipServo_action_node 
sleep 1
rosnode kill /roswww 
#rosnode cleanup
echo "Nodes killed"

