"""autogenerated by genpy from hrl_multimodal_anomaly_detection/CupFinderRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CupFinderRequest(genpy.Message):
  _md5sum = "2044eb57c15e4dce3c879a1a1b124b3b"
  _type = "hrl_multimodal_anomaly_detection/CupFinderRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 pixel_u
int32 pixel_v

"""
  __slots__ = ['pixel_u','pixel_v']
  _slot_types = ['int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pixel_u,pixel_v

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CupFinderRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pixel_u is None:
        self.pixel_u = 0
      if self.pixel_v is None:
        self.pixel_v = 0
    else:
      self.pixel_u = 0
      self.pixel_v = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.pixel_u, _x.pixel_v))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.pixel_u, _x.pixel_v,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.pixel_u, _x.pixel_v))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.pixel_u, _x.pixel_v,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i = struct.Struct("<2i")
"""autogenerated by genpy from hrl_multimodal_anomaly_detection/CupFinderResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class CupFinderResponse(genpy.Message):
  _md5sum = "bac764537310ba8703643eb02ade4505"
  _type = "hrl_multimodal_anomaly_detection/CupFinderResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PoseStamped pixel3d
uint8 error_flag
uint8 SUCCESS=0
uint8 NO_CAMERA_INFO=1
uint8 NO_POINT_CLOUD=2
uint8 OUTSIDE_IMAGE=3
uint8 OUTSIDE_POINT_CLOUD=4


================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  # Pseudo-constants
  SUCCESS = 0
  NO_CAMERA_INFO = 1
  NO_POINT_CLOUD = 2
  OUTSIDE_IMAGE = 3
  OUTSIDE_POINT_CLOUD = 4

  __slots__ = ['pixel3d','error_flag']
  _slot_types = ['geometry_msgs/PoseStamped','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pixel3d,error_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CupFinderResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pixel3d is None:
        self.pixel3d = geometry_msgs.msg.PoseStamped()
      if self.error_flag is None:
        self.error_flag = 0
    else:
      self.pixel3d = geometry_msgs.msg.PoseStamped()
      self.error_flag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.pixel3d.header.seq, _x.pixel3d.header.stamp.secs, _x.pixel3d.header.stamp.nsecs))
      _x = self.pixel3d.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7dB.pack(_x.pixel3d.pose.position.x, _x.pixel3d.pose.position.y, _x.pixel3d.pose.position.z, _x.pixel3d.pose.orientation.x, _x.pixel3d.pose.orientation.y, _x.pixel3d.pose.orientation.z, _x.pixel3d.pose.orientation.w, _x.error_flag))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pixel3d is None:
        self.pixel3d = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pixel3d.header.seq, _x.pixel3d.header.stamp.secs, _x.pixel3d.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pixel3d.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pixel3d.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.pixel3d.pose.position.x, _x.pixel3d.pose.position.y, _x.pixel3d.pose.position.z, _x.pixel3d.pose.orientation.x, _x.pixel3d.pose.orientation.y, _x.pixel3d.pose.orientation.z, _x.pixel3d.pose.orientation.w, _x.error_flag,) = _struct_7dB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.pixel3d.header.seq, _x.pixel3d.header.stamp.secs, _x.pixel3d.header.stamp.nsecs))
      _x = self.pixel3d.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7dB.pack(_x.pixel3d.pose.position.x, _x.pixel3d.pose.position.y, _x.pixel3d.pose.position.z, _x.pixel3d.pose.orientation.x, _x.pixel3d.pose.orientation.y, _x.pixel3d.pose.orientation.z, _x.pixel3d.pose.orientation.w, _x.error_flag))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pixel3d is None:
        self.pixel3d = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pixel3d.header.seq, _x.pixel3d.header.stamp.secs, _x.pixel3d.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pixel3d.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pixel3d.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.pixel3d.pose.position.x, _x.pixel3d.pose.position.y, _x.pixel3d.pose.position.z, _x.pixel3d.pose.orientation.x, _x.pixel3d.pose.orientation.y, _x.pixel3d.pose.orientation.z, _x.pixel3d.pose.orientation.w, _x.error_flag,) = _struct_7dB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7dB = struct.Struct("<7dB")
class CupFinder(object):
  _type          = 'hrl_multimodal_anomaly_detection/CupFinder'
  _md5sum = '77d375efc96312100499b2b8d5091377'
  _request_class  = CupFinderRequest
  _response_class = CupFinderResponse
