#!/usr/bin/env python

import rospy
from hrl_task_planning.msg import PDDLProblem

if __name__ == '__main__':
    rospy.init_node('planning_test_node')
    test_pub = rospy.Publisher('/perform_task', PDDLProblem, latch=True)
    msg = PDDLProblem()
    # msg.name = "test_problem"
    # msg.domain = "shaving"
    # msg.init = ["(at pr2 user-right)", "(at ROUND-MIRROR TOOLBOX)", "(at SHAVER TOOLBOX)"]
    msg.name = "test_problem"
    msg.domain = "move_object"
    msg.objects = []
    msg.init = []
    msg.goal = []
    test_pub.publish(msg)
    rospy.spin()
