"""autogenerated by genpy from assistive_teleop/FtHoldGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class FtHoldGoal(genpy.Message):
  _md5sum = "856fd0ae1f900ee5850cbe1b1da3c1c2"
  _type = "assistive_teleop/FtHoldGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float32 activity_thresh
float32 z_thresh
float32 mag_thresh
duration timeout

"""
  __slots__ = ['activity_thresh','z_thresh','mag_thresh','timeout']
  _slot_types = ['float32','float32','float32','duration']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       activity_thresh,z_thresh,mag_thresh,timeout

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FtHoldGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.activity_thresh is None:
        self.activity_thresh = 0.
      if self.z_thresh is None:
        self.z_thresh = 0.
      if self.mag_thresh is None:
        self.mag_thresh = 0.
      if self.timeout is None:
        self.timeout = genpy.Duration()
    else:
      self.activity_thresh = 0.
      self.z_thresh = 0.
      self.mag_thresh = 0.
      self.timeout = genpy.Duration()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3f2i.pack(_x.activity_thresh, _x.z_thresh, _x.mag_thresh, _x.timeout.secs, _x.timeout.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.timeout is None:
        self.timeout = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.activity_thresh, _x.z_thresh, _x.mag_thresh, _x.timeout.secs, _x.timeout.nsecs,) = _struct_3f2i.unpack(str[start:end])
      self.timeout.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3f2i.pack(_x.activity_thresh, _x.z_thresh, _x.mag_thresh, _x.timeout.secs, _x.timeout.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.timeout is None:
        self.timeout = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.activity_thresh, _x.z_thresh, _x.mag_thresh, _x.timeout.secs, _x.timeout.nsecs,) = _struct_3f2i.unpack(str[start:end])
      self.timeout.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3f2i = struct.Struct("<3f2i")
