"""autogenerated by genpy from hrl_head_registration/HeadRegistrationRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HeadRegistrationRequest(genpy.Message):
  _md5sum = "187c392235727ec43339108b21286363"
  _type = "hrl_head_registration/HeadRegistrationRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 u
uint32 v

"""
  __slots__ = ['u','v']
  _slot_types = ['uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       u,v

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HeadRegistrationRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.u is None:
        self.u = 0
      if self.v is None:
        self.v = 0
    else:
      self.u = 0
      self.v = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.u, _x.v))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.u, _x.v,) = _struct_2I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.u, _x.v))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.u, _x.v,) = _struct_2I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I = struct.Struct("<2I")
"""autogenerated by genpy from hrl_head_registration/HeadRegistrationResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class HeadRegistrationResponse(genpy.Message):
  _md5sum = "0de00547a6db62eea5a8c01189bc537a"
  _type = "hrl_head_registration/HeadRegistrationResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool success
geometry_msgs/PoseStamped reg_pose


================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['success','reg_pose']
  _slot_types = ['bool','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,reg_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HeadRegistrationResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.reg_pose is None:
        self.reg_pose = geometry_msgs.msg.PoseStamped()
    else:
      self.success = False
      self.reg_pose = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B3I.pack(_x.success, _x.reg_pose.header.seq, _x.reg_pose.header.stamp.secs, _x.reg_pose.header.stamp.nsecs))
      _x = self.reg_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.reg_pose.pose.position.x, _x.reg_pose.pose.position.y, _x.reg_pose.pose.position.z, _x.reg_pose.pose.orientation.x, _x.reg_pose.pose.orientation.y, _x.reg_pose.pose.orientation.z, _x.reg_pose.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.reg_pose is None:
        self.reg_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.success, _x.reg_pose.header.seq, _x.reg_pose.header.stamp.secs, _x.reg_pose.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reg_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.reg_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.reg_pose.pose.position.x, _x.reg_pose.pose.position.y, _x.reg_pose.pose.position.z, _x.reg_pose.pose.orientation.x, _x.reg_pose.pose.orientation.y, _x.reg_pose.pose.orientation.z, _x.reg_pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B3I.pack(_x.success, _x.reg_pose.header.seq, _x.reg_pose.header.stamp.secs, _x.reg_pose.header.stamp.nsecs))
      _x = self.reg_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.reg_pose.pose.position.x, _x.reg_pose.pose.position.y, _x.reg_pose.pose.position.z, _x.reg_pose.pose.orientation.x, _x.reg_pose.pose.orientation.y, _x.reg_pose.pose.orientation.z, _x.reg_pose.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.reg_pose is None:
        self.reg_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.success, _x.reg_pose.header.seq, _x.reg_pose.header.stamp.secs, _x.reg_pose.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reg_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.reg_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.reg_pose.pose.position.x, _x.reg_pose.pose.position.y, _x.reg_pose.pose.position.z, _x.reg_pose.pose.orientation.x, _x.reg_pose.pose.orientation.y, _x.reg_pose.pose.orientation.z, _x.reg_pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7d = struct.Struct("<7d")
_struct_B3I = struct.Struct("<B3I")
class HeadRegistration(object):
  _type          = 'hrl_head_registration/HeadRegistration'
  _md5sum = '4f17c68605ed53045ecaf9e3b75e91c4'
  _request_class  = HeadRegistrationRequest
  _response_class = HeadRegistrationResponse
