# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arm_cart_control_gui.ui'
#
# Created: Thu Apr 12 20:42:17 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(702, 505)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.layoutWidget = QtGui.QWidget(Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 110, 321, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.rotate_x_pos = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_x_pos.sizePolicy().hasHeightForWidth())
        self.rotate_x_pos.setSizePolicy(sizePolicy)
        self.rotate_x_pos.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_x_pos.setStyleSheet("image: url(:/resources/rotate_x_neg_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.rotate_x_pos.setText("")
        self.rotate_x_pos.setObjectName("rotate_x_pos")
        self.gridLayout.addWidget(self.rotate_x_pos, 0, 0, 1, 1)
        self.rotate_y_pos = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_y_pos.sizePolicy().hasHeightForWidth())
        self.rotate_y_pos.setSizePolicy(sizePolicy)
        self.rotate_y_pos.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_y_pos.setStyleSheet("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.rotate_y_pos.setText("")
        self.rotate_y_pos.setObjectName("rotate_y_pos")
        self.gridLayout.addWidget(self.rotate_y_pos, 0, 1, 1, 1)
        self.rotate_x_neg = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_x_neg.sizePolicy().hasHeightForWidth())
        self.rotate_x_neg.setSizePolicy(sizePolicy)
        self.rotate_x_neg.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_x_neg.setStyleSheet("image: url(:/resources/rotate_x_pos_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.rotate_x_neg.setText("")
        self.rotate_x_neg.setObjectName("rotate_x_neg")
        self.gridLayout.addWidget(self.rotate_x_neg, 0, 2, 1, 1)
        self.rotate_z_neg = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_z_neg.sizePolicy().hasHeightForWidth())
        self.rotate_z_neg.setSizePolicy(sizePolicy)
        self.rotate_z_neg.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_z_neg.setStyleSheet("image: url(:/resources/rotate_z_neg_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.rotate_z_neg.setText("")
        self.rotate_z_neg.setObjectName("rotate_z_neg")
        self.gridLayout.addWidget(self.rotate_z_neg, 1, 0, 1, 1)
        self.rotate_z_pos = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_z_pos.sizePolicy().hasHeightForWidth())
        self.rotate_z_pos.setSizePolicy(sizePolicy)
        self.rotate_z_pos.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_z_pos.setStyleSheet("image: url(:/resources/rotate_z_pos_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.rotate_z_pos.setText("")
        self.rotate_z_pos.setObjectName("rotate_z_pos")
        self.gridLayout.addWidget(self.rotate_z_pos, 1, 2, 1, 1)
        self.rotate_y_neg = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_y_neg.sizePolicy().hasHeightForWidth())
        self.rotate_y_neg.setSizePolicy(sizePolicy)
        self.rotate_y_neg.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_y_neg.setStyleSheet("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.rotate_y_neg.setText("")
        self.rotate_y_neg.setObjectName("rotate_y_neg")
        self.gridLayout.addWidget(self.rotate_y_neg, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("background-image: url(:/resources/empty.png);\n"
"image: url(:/resources/tool_direction.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.reset_rotation = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_rotation.sizePolicy().hasHeightForWidth())
        self.reset_rotation.setSizePolicy(sizePolicy)
        self.reset_rotation.setBaseSize(QtCore.QSize(80, 80))
        self.reset_rotation.setStyleSheet("font: 16pt ;\n"
"background-image: url(:/resources/empty.png);")
        self.reset_rotation.setObjectName("reset_rotation")
        self.gridLayout.addWidget(self.reset_rotation, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(470, 70, 151, 31))
        self.label_5.setStyleSheet("font: 20pt;")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtGui.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 151, 31))
        self.label_4.setStyleSheet("font: 20pt;")
        self.label_4.setObjectName("label_4")
        self.layoutWidget_2 = QtGui.QWidget(Frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 110, 321, 311))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.translate_up = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_up.sizePolicy().hasHeightForWidth())
        self.translate_up.setSizePolicy(sizePolicy)
        self.translate_up.setBaseSize(QtCore.QSize(80, 80))
        self.translate_up.setStyleSheet("image: url(:/resources/translate_up_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.translate_up.setText("")
        self.translate_up.setObjectName("translate_up")
        self.gridLayout_2.addWidget(self.translate_up, 0, 1, 1, 1)
        self.translate_left = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_left.sizePolicy().hasHeightForWidth())
        self.translate_left.setSizePolicy(sizePolicy)
        self.translate_left.setBaseSize(QtCore.QSize(80, 80))
        self.translate_left.setStyleSheet("image: url(:/resources/translate_left_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.translate_left.setText("")
        self.translate_left.setObjectName("translate_left")
        self.gridLayout_2.addWidget(self.translate_left, 1, 0, 1, 1)
        self.translate_right = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_right.sizePolicy().hasHeightForWidth())
        self.translate_right.setSizePolicy(sizePolicy)
        self.translate_right.setBaseSize(QtCore.QSize(80, 80))
        self.translate_right.setStyleSheet("image: url(:/resources/translate_right_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.translate_right.setText("")
        self.translate_right.setObjectName("translate_right")
        self.gridLayout_2.addWidget(self.translate_right, 1, 2, 1, 1)
        self.translate_down = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_down.sizePolicy().hasHeightForWidth())
        self.translate_down.setSizePolicy(sizePolicy)
        self.translate_down.setBaseSize(QtCore.QSize(80, 80))
        self.translate_down.setStyleSheet("image: url(:/resources/translate_down_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.translate_down.setText("")
        self.translate_down.setObjectName("translate_down")
        self.gridLayout_2.addWidget(self.translate_down, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setStyleSheet("background-image: url(:/resources/empty.png);\n"
"image: url(:/resources/tool_direction.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.translate_out = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_out.sizePolicy().hasHeightForWidth())
        self.translate_out.setSizePolicy(sizePolicy)
        self.translate_out.setBaseSize(QtCore.QSize(80, 80))
        self.translate_out.setStyleSheet("image: url(:/resources/translate_out_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.translate_out.setText("")
        self.translate_out.setObjectName("translate_out")
        self.gridLayout_2.addWidget(self.translate_out, 0, 2, 1, 1)
        self.translate_in = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_in.sizePolicy().hasHeightForWidth())
        self.translate_in.setSizePolicy(sizePolicy)
        self.translate_in.setBaseSize(QtCore.QSize(80, 80))
        self.translate_in.setStyleSheet("image: url(:/resources/translate_in_on.png);\n"
"background-image: url(:/resources/empty.png);")
        self.translate_in.setText("")
        self.translate_in.setObjectName("translate_in")
        self.gridLayout_2.addWidget(self.translate_in, 0, 0, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(Frame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 3, 661, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("font: 20pt ;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.controller_name = QtGui.QLabel(self.layoutWidget_3)
        self.controller_name.setStyleSheet("font: 20pt ;")
        self.controller_name.setObjectName("controller_name")
        self.horizontalLayout_2.addWidget(self.controller_name)
        self.widget = QtGui.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(20, 440, 661, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 20pt ;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.status_text = QtGui.QLabel(self.widget)
        self.status_text.setStyleSheet("font: 20pt ;")
        self.status_text.setObjectName("status_text")
        self.horizontalLayout.addWidget(self.status_text)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_rotation.setText(QtGui.QApplication.translate("Frame", "Reset\n"
"Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Translation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Controller:", None, QtGui.QApplication.UnicodeUTF8))
        self.controller_name.setText(QtGui.QApplication.translate("Frame", "Current Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.status_text.setText(QtGui.QApplication.translate("Frame", "Current Status", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
